[versions]
vaadin = "24.3.8"
# https://repo1.maven.org/maven2/org/slf4j/slf4j-api/
slf4j = "2.0.12"
vok = "0.17.1"

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
vaadin-boot = "com.github.mvysny.vaadin-boot:vaadin-boot:12.2"
vaadin-core = { module = "com.vaadin:vaadin-core", version.ref = "vaadin" }
junit-platform-launcher = "org.junit.platform:junit-platform-launcher:1.10.2"
karibu-testing = "com.github.mvysny.kaributesting:karibu-testing-v24:2.1.5"
karibu-dsl = "com.github.mvysny.karibudsl:karibu-dsl-v23:2.1.3"
flyway = "org.flywaydb:flyway-core:10.11.0"
h2 = "com.h2database:h2:2.2.224"
hikaricp = "com.zaxxer:HikariCP:5.1.0"
dynatest = "com.github.mvysny.dynatest:dynatest:0.25"
vok-db = { module = "eu.vaadinonkotlin:vok-framework-vokdb", version.ref = "vok" }
hibernate-validator = "org.hibernate.validator:hibernate-validator:8.0.1.Final"

[plugins]
vaadin = { id = "com.vaadin", version.ref = "vaadin" }
