[versions]
vaadin = "24.6.2"
# https://repo1.maven.org/maven2/org/slf4j/slf4j-api/
slf4j = "2.0.16"
vok = "0.18"

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
vaadin-boot = "com.github.mvysny.vaadin-boot:vaadin-boot:13.3"
vaadin-core = { module = "com.vaadin:vaadin-core", version.ref = "vaadin" }
karibu-testing = "com.github.mvysny.kaributesting:karibu-testing-v24:2.2.0"
karibu-dsl = "com.github.mvysny.karibudsl:karibu-dsl-v23:2.2.0"
flyway = "org.flywaydb:flyway-core:10.15.2"
h2 = "com.h2database:h2:2.2.224"
hikaricp = "com.zaxxer:HikariCP:5.1.0"
junit = "org.junit.jupiter:junit-jupiter-engine:5.11.0"
vok-db = { module = "eu.vaadinonkotlin:vok-framework-vokdb", version.ref = "vok" }
hibernate-validator = "org.hibernate.validator:hibernate-validator:8.0.1.Final"

[plugins]
vaadin = { id = "com.vaadin", version.ref = "vaadin" }
