[versions]
vaadin = "25.0.4"
# https://repo1.maven.org/maven2/org/slf4j/slf4j-api/
slf4j = "2.0.17"
vok = "0.18.1"

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
vaadinboot = "com.github.mvysny.vaadin-boot:vaadin-boot:13.6"
vaadin-core = { module = "com.vaadin:vaadin-core", version.ref = "vaadin" }
vaadin-dev = { module = "com.vaadin:vaadin-dev", version.ref = "vaadin" }
karibu-testing = "com.github.mvysny.kaributesting:karibu-testing-v24:2.6.2"
karibu-dsl = "com.github.mvysny.karibudsl:karibu-dsl-v23:2.5.0"
flyway = "org.flywaydb:flyway-core:10.15.2"
h2 = "com.h2database:h2:2.2.224"
hikaricp = "com.zaxxer:HikariCP:7.0.2"
junit = "org.junit.jupiter:junit-jupiter-engine:6.0.1"
vok-db = { module = "eu.vaadinonkotlin:vok-framework-vokdb", version.ref = "vok" }
hibernate-validator = "org.hibernate.validator:hibernate-validator:9.1.0.Final"

[plugins]
vaadin = { id = "com.vaadin", version.ref = "vaadin" }
